import { NextResponse } from "next/server";
import { glossaryTerms } from "../../src/data/glossary";
import { pillars } from "../../src/data/pillars";
import { topics } from "../../src/data/topics";
import { servers } from "../../src/data/servers";
import { docsPages, getDocsPath } from "../../src/data/docs";
import { blogPosts } from "../../src/data/blogPosts";
import { siteConfig } from "../../src/data/site";

export const dynamic = "force-static";

const baseUrl = siteConfig.url.replace(/\/$/, "");

export async function GET() {
  const today = new Date().toISOString().split("T")[0];

  const header = `# MCPserver.in - Full Published Knowledge Index

> Canonical machine-readable index for AI agents, RAG systems, answer engines, and search crawlers.
> This index lists published content metadata and relationships. It does not claim that every generated candidate page is indexable.
> Canonical origin: ${baseUrl}
> Last updated: ${today}

---

## 1. Primary Protocol Entity

### Model Context Protocol (MCP)
- **Definition:** An open protocol for connecting AI applications to external tools, resources, and prompts through a standardized client-server interface.
- **Canonical entity:** ${baseUrl}/mcp-protocol/
- **Specification:** https://modelcontextprotocol.io/specification/
- **Message format:** JSON-RPC 2.0
- **Core primitives:** Tools, Resources, Prompts
- **Transports:** stdio, Server-Sent Events (SSE), Streamable HTTP

---

## 2. Pillar Pages (${pillars.length})

`;

  const pillarSection = pillars.map((p) => `### ${p.title}
- URL: ${baseUrl}/${p.slug}/
- Description: ${p.description}
- Direct answer: ${p.shortAnswer}
- Primary keyword: ${p.primaryKeyword}
`).join("\n");

  const topicSection = `
---

## 3. Topic Pages (${topics.length})

${topics.map((t) => `### ${t.title}
- URL: ${baseUrl}/topics/${t.slug}/
- Description: ${t.explanation}
- Key takeaway: ${t.shortAnswer}
`).join("\n")}`;

  const serverSection = `
---

## 4. MCP Server Directory (${servers.length})

${servers.map((s) => `### ${s.name}
- URL: ${baseUrl}/servers/${s.slug}/
- Category: ${s.category}
- Description: ${s.description}
- Authentication: ${s.auth}
- Use cases: ${s.useCases.join("; ")}
- Features: ${s.features.join("; ")}
`).join("\n")}`;

  const docsSection = `
---

## 5. Documentation (${docsPages.length})

${docsPages.map((doc) => `### ${doc.title}
- URL: ${baseUrl}${getDocsPath(doc)}/
- Category: ${doc.category}
- Description: ${doc.description}
- Direct answer: ${doc.directAnswer}
- Schema type: ${doc.schemaType}
- Related: ${doc.related.join(", ")}
`).join("\n")}`;

  const blogSection = `
---

## 6. Blog Posts (${blogPosts.length})

${blogPosts.map((post) => `### ${post.title}
- URL: ${baseUrl}/blog/${post.slug}/
- Date: ${post.date}
- Category: ${post.category}
- Excerpt: ${post.excerpt}
- Keywords: ${post.keywords.join(", ")}
`).join("\n")}`;

  const glossarySection = `
---

## 7. Glossary (${glossaryTerms.length} defined terms)

${glossaryTerms.map((g) => `### ${g.term}
- URL: ${baseUrl}/glossary/${g.slug}/
- Definition: ${g.definition}
- Detailed explanation: ${g.detailedExplanation}
- Key takeaways: ${g.keyTakeaways?.join(", ") || "N/A"}
- Protocol layer: ${g.technicalDetails.protocolLayer || "N/A"}
- Format: ${g.technicalDetails.format || "N/A"}
- Latency profile: ${g.technicalDetails.latencyProfile || "N/A"}
- Use case: ${g.useCase || "N/A"}
- References: ${g.references.join(", ")}
`).join("\n")}`;

  const footer = `
---

## 8. Canonical Machine Endpoints
- Sitemap: ${baseUrl}/sitemap.xml
- LLM summary: ${baseUrl}/llms.txt
- Full index: ${baseUrl}/llms-full.txt
- Security: ${baseUrl}/security/
- Editorial policy: ${baseUrl}/editorial-policy/
- Privacy: ${baseUrl}/privacy/
- Terms: ${baseUrl}/terms/

## 9. Entity and Source Notes
- MCP specification: https://modelcontextprotocol.io/specification/
- JSON-RPC 2.0 specification: https://www.jsonrpc.org/specification
- Content is generated from structured repository datasets at build time.
- URLs in this index use the canonical apex origin and normalized trailing-slash form.

*Generated by MCPserver.in for machine-readable discovery.*
`;

  return new NextResponse(header + pillarSection + topicSection + serverSection + docsSection + blogSection + glossarySection + footer, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, stale-while-revalidate=1800",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
