import { NextResponse } from "next/server";
import { glossaryTerms } from "../../src/data/glossary";
import { pillars } from "../../src/data/pillars";
import { topics } from "../../src/data/topics";
import { siteConfig } from "../../src/data/site";

export const dynamic = "force-static";

export async function GET() {
  const today = new Date().toISOString().split("T")[0];
  
  const header = `# MCPserver.in - Full Knowledge Graph (AI Agent Index)

> This document represents the complete structured entities, relationships, and metadata of the MCPserver.in ecosystem for AI agents, RAG systems, and answer engines.
> Last Updated: ${today}

---

## 1. Primary Protocol Entities

### Entity: Model Context Protocol (MCP)
- **Definition:** An open, secure protocol that standardizes how artificial intelligence agents and large language models (LLMs) exchange context, tools, prompts, and data resources with external servers.
- **Alternative Name:** MCP
- **Standard Transport Layers:**
  - \`stdio\`: Local process communication over standard input/output channels.
  - \`SSE\` (Server-Sent Events): Remote HTTP connections for decoupled setups.
- **Message Protocol:** Strictly compliant with the JSON-RPC 2.0 specification.
- **Core Capabilities:**
  - **Tools:** Enabling models to perform tasks (e.g., query SQL, write files, call APIs).
  - **Resources:** Exposing static or dynamic read-only data (e.g., log dumps, DB schemas).
  - **Prompts:** Offering reusable prompt templates directly from the server.

---

## 2. Core Protocol Pillars

`;

  const pillarSection = pillars.map(p => `### Pillar: ${p.title}
- **Slug:** \`${p.slug}\`
- **Definition:** ${p.description}
- **Direct Answer:** ${p.shortAnswer}
- **Primary Keyword:** ${p.primaryKeyword}

`).join("\\n");

  const topicSection = `

---

## 3. MCP Topics

`;

  const topicsContent = topics.map(t => `### Topic: ${t.title}
- **Slug:** \`${t.slug}\`
- **Definition:** ${t.explanation}
- **Key Takeaway:** ${t.shortAnswer}

`).join("\\n");

  const glossarySection = `

---

## 4. Glossary Terms (${glossaryTerms.length} defined terms)

`;

  const glossaryContent = glossaryTerms.map(g => `### Term: ${g.term}
- **Slug:** \`${g.slug}\`
- **Definition:** ${g.definition}
- **Detailed Explanation:** ${g.detailedExplanation}
- **Key Takeaways:** ${g.keyTakeaways ? g.keyTakeaways.join(", ") : "N/A"}
- **Technical Details:**
  - Protocol Layer: ${g.technicalDetails.protocolLayer || "N/A"}
  - Format: ${g.technicalDetails.format || "N/A"}
  - Latency Profile: ${g.technicalDetails.latencyProfile || "N/A"}
- **Use Case:** ${g.useCase || "N/A"}
- **References:** ${g.references.join(", ")}

`).join("\\n");

  const footer = `

---

## 5. Documentation Knowledge Base

### Clusters:
- Getting Started: MCP concepts, local installation, Claude and Cursor configuration, managed edge hosting.
- Protocol: Tools, resources, prompts, events, JSON-RPC, stdio, and SSE concepts for MCP builders.
- Pricing: India-aware hosting costs, free vs paid, hidden operational costs, enterprise security and VAPT planning.
- Performance: Bengaluru vs Mumbai placement, global vs India hosting, payload optimization, latency benchmarking.
- Compliance: DPDP-aware implementation, PII redaction, audit logs, RBI-aware fintech controls, secure tool design.
- Comparisons: MCP vs REST, GraphQL, API gateways, and when-to-use-MCP decision guides.
- Deployment: Railway, AWS EC2, Google Cloud Run, Vercel, Kubernetes, environment variables, health checks, rollout patterns.
- Industry: Indian startup, fintech, ecommerce, government, healthcare, and education workflows with sector-specific safety controls.
- Monitoring: Grafana dashboards, MCP Pulse-style checks, logs, traces, redaction metrics, and incident workflows.

---

## 6. Contact & Institutional Trust
- **Publisher:** ${siteConfig.brand}
- **Support Contact:** ${siteConfig.company.email}
- **Legal Compliance:** Designed for secure, compliant production MCP workflows on robust edge infrastructure.

---

*Generated by MCPserver.in Knowledge Graph API - For RAG ingestion and AI answer engine indexing.*
`;

  const fullContent = header + pillarSection + topicSection + topicsContent + glossarySection + glossaryContent + footer;

  return new NextResponse(fullContent, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=3600, stale-while-revalidate=1800",
    },
  });
}