import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Drafts - MCPServer.in Editorial",
  description: "Content drafts awaiting review.",
  robots: { index: false, follow: false },
};

export default function AdminDraftsPage() {
  return (
    <div className="max-w-7xl mx-auto p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Drafts</h1>
        <p className="text-sm text-gray-500 mt-1">
          Content drafts generated by the content pipeline.
        </p>
      </div>

      <div className="p-6 border rounded-xl bg-white shadow-sm">
        <p className="text-sm text-gray-600">
          Drafts are generated by the content pipeline and stored for editorial review. Use the content pipeline to generate drafts.
        </p>
      </div>
    </div>
  );
}
