import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Landmark, Lock, ShieldCheck } from "lucide-react";
import Breadcrumbs from "../../../src/components/Breadcrumbs";
import SchemaJsonLd from "../../../src/components/SchemaJsonLd";
import FAQ from "../../../src/components/FAQ";
import MermaidDiagram from "../../../src/components/MermaidDiagram";
import { getUnifiedGraphSchema } from "../../../src/lib/schema";
import { getContentDates } from "../../../src/lib/contentDates";

const title = "RBI Data Localization Rules for AI Agents in Fintech";
const description =
  "What RBI's data localization guidelines mean for MCP servers processing financial transactions: data residency, data minimization, and immutable audit trails.";

export const metadata: Metadata = {
  title,
  description,  alternates: {
    canonical: "/learn/rbi-ai-guidelines",
    languages: {
      "en-IN": "/learn/rbi-ai-guidelines",
      "en": "/learn/rbi-ai-guidelines",
        }
  },

};

const checklist = [
  "MCP server and its database run in an Indian region (e.g. AWS ap-south-1 Mumbai, Azure Central India Pune)",
  "No fallback routing, third-party logging service, or CDN edge cache stores payment data outside India",
  "Database role used by the MCP server is read-only unless a specific, audited write tool requires otherwise",
  "Every tool that touches payment or account data masks identifiers (UPI IDs, account numbers) in outputs and logs",
  "Every tool invocation writes an audit log entry: timestamp, agent ID, hashed user ID, tool name, action, status",
  "Audit logs are stored in append-only, encrypted storage — not a mutable table a service account can edit",
  "TLS 1.3 in transit and AES-256 at rest for anything touching financial data",
  "A documented incident-response path exists for a suspected data exposure",
];

export default function RbiAiGuidelinesPage() {
  const faqs = [
    { question: "Does RBI have rules specifically written for AI agents?", answer: "RBI's data localization framework predates AI agents and was written for payment system data generally. It doesn't name MCP or AI agents specifically, but its requirements apply in full to any system — AI-driven or not — that stores or processes payment system data, which includes an MCP server sitting in front of a payments database." },
    { question: "Can I use a US-based LLM API if my MCP server is hosted in India?", answer: "The data-residency requirement is about where payment system data is stored, not which LLM API you call. In practice: keep the MCP server and its database in India, and don't send raw payment data (account numbers, full transaction details) to a non-Indian LLM in the prompt — aggregate or mask it first." },
    { question: "Is a managed database in Mumbai enough by itself?", answer: "No. Regional hosting satisfies data residency, but RBI-aligned practice also expects access control (least privilege, read-only by default), audit logging, and encryption. Region selection is one requirement among several, not the whole checklist." },
    { question: "What counts as payment system data here?", answer: "Account numbers, UPI IDs, transaction amounts and timestamps, settlement records, and anything else generated by or describing a payment transaction. When in doubt, treat a field as in-scope and mask or minimize it rather than assuming it's exempt." },
  ];

  const dates = getContentDates("learn:rbi-ai-guidelines");
  const unifiedGraphSchema = getUnifiedGraphSchema({
    pageUrl: "/learn/rbi-ai-guidelines",
    title,
    description,
    speakable: ["#rbi-ai-guidelines-page"],
    breadcrumbs: [
      { name: "Learn", item: "/learn" },
      { name: "RBI AI Guidelines", item: "/learn/rbi-ai-guidelines" },
    ],
    article: {
      title,
      description,
      authorName: "MCPserver.in Engineering",
      authorRole: "Infrastructure & Platform Team",
      datePublished: dates.datePublished,
      dateModified: dates.dateModified,
    },
    faq: faqs,
  });

  return (
    <div id="rbi-ai-guidelines-page" className="min-h-screen bg-transparent text-white pt-6 pb-16">
      <SchemaJsonLd schema={unifiedGraphSchema} />

      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        <Breadcrumbs
          items={[
            { name: "Learn", href: "/learn" },
            { name: "RBI AI Guidelines", href: "/learn/rbi-ai-guidelines" },
          ]}
        />

        <section className="py-10 text-center">
          <div className="mx-auto grid h-12 w-12 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-500/10">
            <Landmark className="h-6 w-6 text-cyan-200" />
          </div>
          <h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-5xl">RBI Data Localization Rules for AI Agents</h1>
          <p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed text-white/58">
            What building an MCP server for fintech actually requires under RBI&apos;s data localization expectations — not a legal opinion,
            a practical engineering checklist.
          </p>
        </section>

        <section className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.05] p-6 sm:p-8">
          <p className="text-xs font-bold uppercase tracking-wide text-amber-300">Direct answer</p>
          <p className="mt-3 text-sm leading-relaxed text-white/80">
            RBI requires that payment system data be stored exclusively in India. An MCP server processing financial transactions should
            enforce data residency (host in an Indian region), data minimization (mask identifiers in tool outputs), and immutable audit
            logging (record every tool call). This page covers the engineering side; it is not legal advice — confirm your specific
            obligations with qualified counsel or a compliance officer before shipping.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-black text-white mb-6">The 3 pillars</h2>
          <div className="grid gap-6 sm:grid-cols-3">
            <div className="rounded-xl border border-white/10 bg-white/[0.02] p-5">
              <ShieldCheck className="h-5 w-5 text-cyan-300 mb-3" />
              <h3 className="text-sm font-black text-white mb-2">1. Data residency</h3>
              <p className="text-xs leading-relaxed text-white/60">
                Host the MCP server and its underlying database in an Indian region — AWS ap-south-1 (Mumbai) or Azure Central India
                (Pune) are the common choices. No fallback routing or third-party service outside India should touch payment data.
              </p>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/[0.02] p-5">
              <Lock className="h-5 w-5 text-cyan-300 mb-3" />
              <h3 className="text-sm font-black text-white mb-2">2. Data minimization</h3>
              <p className="text-xs leading-relaxed text-white/60">
                Tools should return only what's needed and mask the rest — a UPI ID should come back as{" "}
                <code className="text-cyan-200">xy***@bank</code>, not in full, unless a specific tool has an audited reason to reveal it.
              </p>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/[0.02] p-5">
              <CheckCircle2 className="h-5 w-5 text-cyan-300 mb-3" />
              <h3 className="text-sm font-black text-white mb-2">3. Immutable audit trails</h3>
              <p className="text-xs leading-relaxed text-white/60">
                Log every tools/call with a timestamp, agent ID, hashed user ID, and outcome, written to append-only storage that a
                compromised service account can&apos;t quietly edit.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-12 rounded-2xl border border-white/10 bg-white/[0.02] p-6 sm:p-8">
          <h2 className="text-2xl font-black text-white mb-4">Reference architecture</h2>
          <p className="text-sm text-white/58 mb-2">
            A minimal RBI-aligned flow: the agent never talks to the database directly, every read goes through the MCP server, and every
            call is logged before the response returns.
          </p>
          <MermaidDiagram
            chart={`graph LR
  A[AI Agent] -->|tools/call| B[MCP Server - Mumbai]
  B -->|read-only query| C[(PostgreSQL - Mumbai)]
  C -->|masked result| B
  B -->|audit entry| D[(S3 Audit Log - Mumbai)]
  B -->|JSON response| A`}
          />
        </section>

        <section className="mt-12 rounded-2xl border border-white/10 bg-white/[0.02] p-6 sm:p-8">
          <h2 className="text-2xl font-black text-white mb-4">Pre-deployment checklist</h2>
          <ul className="space-y-3">
            {checklist.map((item) => (
              <li key={item} className="flex items-start gap-3 text-sm text-white/70">
                <span className="mt-0.5 shrink-0 rounded border border-white/20 bg-white/[0.03] px-1.5 py-0.5 text-[10px] font-bold text-white/40">
                  [ ]
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <FAQ items={faqs} title="RBI AI Guidelines: FAQs" subtitle="Common questions for fintech teams building MCP servers." />

        <section className="mt-4 grid gap-6 sm:grid-cols-2">
          <Link href="/docs/industry/upi-integration" className="group rounded-xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-cyan-300/40">
            <div className="flex items-center gap-2 mb-2">
              <Landmark className="h-4 w-4 text-cyan-300" />
              <h3 className="text-sm font-black text-white group-hover:text-cyan-200">UPI Integration Guide</h3>
            </div>
            <p className="text-xs text-white/55">Initiating and verifying UPI payments from an MCP server, with masked logging.</p>
          </Link>
          <Link href="/docs/compliance/dpdp-checklist" className="group rounded-xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-cyan-300/40">
            <div className="flex items-center gap-2 mb-2">
              <ShieldCheck className="h-4 w-4 text-cyan-300" />
              <h3 className="text-sm font-black text-white group-hover:text-cyan-200">DPDP MCP Checklist</h3>
            </div>
            <p className="text-xs text-white/55">The broader personal-data compliance checklist this page's audit-logging section builds on.</p>
          </Link>
        </section>

        <div className="mt-12">
          <Link href="/learn" className="inline-flex items-center gap-1 text-xs font-bold text-cyan-300 hover:text-cyan-200 transition-colors">
            <BookOpen className="h-3.5 w-3.5" /> Back to MCP Knowledge Hub
          </Link>
        </div>
      </div>
    </div>
  );
}
